export {default as Header} from "./header/Header";
export {default as Discover} from "./discover/Discover";
export {default as Consultation} from "./consultation/Consultation";
export {default as CTA} from "./cta/CTA";
export {default as Approach} from "./approach/Approach";
export {default as Story} from "./story/Story";
export {default as Expert} from "./expert/Expert";
export {default as CTD} from "./ctd/CTD";
export {default as Footer} from "./footer/Footer";